application:
  name: '@project.artifactId@'
  description: '@project.description@'
  version: '@project.version@'

server:
  port: 8080

spring:
  application:
    name: spaceship-manager
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
        one-indexed-parameters: false
        max-page-size: 100

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/"

open-api:
  header:
    pagination:
      enabled: false
